name: Automatic Backup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run backup every day at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests (if any)
      run: |
        echo "Running basic checks..."
        python -c "import sys; print('Python version:', sys.version)"
        
    - name: Create backup timestamp
      run: |
        echo "Backup completed at $(date)" >> backup_log.txt
        echo "Repository: ${{ github.repository }}" >> backup_log.txt
        echo "Commit: ${{ github.sha }}" >> backup_log.txt
        
    - name: Upload backup log
      uses: actions/upload-artifact@v3
      with:
        name: backup-log-${{ github.run_number }}
        path: backup_log.txt 